### ISSUE TITLE
Integer gravity is no longer processed correctly by Blitline

### ISSUE THREAD

**Issue by osharper** [gdoubleultd/Blitline.Net#18]
Try to use two jsons [here](http://www.blitline.com/v3/home/gist?gist_id=5109149):
`"functions":[
        {
            "name":"crop",
            "params":{
                "gravity": "NorthWestGravity",
                "only_shrink_larger" : true,
                "width":720,
                "height": 100
            },
            "save":{
                "extension":".png",
                "image_identifier":"MY_CLIENT_ID",
                "png_quantize":true
            }
        }
    ]`
and
`"functions":[
        {
            "name":"crop",
            "params":{
                "gravity": 1,
                "only_shrink_larger" : true,
                "width":720,
                "height": 100
            },
            "save":{
                "extension":".png",
                "image_identifier":"MY_CLIENT_ID",
                "png_quantize":true
            }
        }
    ]`

and compare the results.
Currently Blitline.net sends gravity value as integer (like in the second json).

**Comment by gwilliams** [comment]
Fixed: #20 ... just need to rebuild the nuget package

**Comment by gwilliams** [comment]
0.6.3 published

**Comment by osharper** [comment]
thanks for that
