### ISSUE TITLE
Lack of information in Response.Image class

### ISSUE THREAD

**Issue by osharper** [gdoubleultd/Blitline.Net#19]
AzureUrl and Meta dictionary needed

**Comment by gwilliams** [comment]
I cannot find any information in the docs regarding AzureUrl. Could you supply an example JSON response?

As for the meta dictionary, this appears to only be returned via polling or postback. The job wrapper that Blitline.Net provides doesn't support the handling of either polling or postback (you can set the url but you have to process the response yourself)

**Comment by osharper** [comment]
this is what appers on my dashboard after I run a job with saving to some `azure_destination`:
 `Image results -> [
    {
        "image_identifier":"6fe3737b-a82c-45fb-995d-d3c694a5c4cc",
        "azure_url":"https://***.blob.core.windows.net/foo/bar.png",
        "meta":{
            "width":273,
            "height":193
        }
    }
]`

I think this might be available for .net client in the same manner as `s3_url`. This is not critical of course.

**Comment by gwilliams** [comment]
Added azure_url into build 0.6.3

**Comment by osharper** [comment]
thank you!
