### ISSUE TITLE
NuGet: cannot resovle dependency Misrosoft.Bcl.Build >=1.1.21

### ISSUE THREAD

**Issue by osharper** [gdoubleultd/Blitline.Net#21]
I think, it's just a misprint and you mean 1.**0**.21 that is currently the latest in NuGet. However, do you really need to be that strict? I think it's nothing wrong to use your library with an older Bcl version.

**Comment by bbceg** [comment]
Am I right in thinking it is impossible to install this package via NuGet until this has been corrected? I'm struggling to install it manually.

**Comment by gwilliams** [comment]
Yeah, apologies about this. For last build was done using Xamarin studio on a Mac and has obviously screwed the nuget packages up.

If I have time I will push a new build out today but you know you could always just raise a pull request to fix the issue and I'll publish the package

**Comment by bbceg** [comment]
Absolutely, would definitely do that if I had before and wasn't worried about messing something up! Very happy to give it a go though, will do so now.

**Comment by gwilliams** [comment]
Reverted change to 1.0.21 and published 0.6.5 build to nuget.org
